# Generated by Django 4.2.13 on 2024-07-15 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_orders_products_rename_customer_customers_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
