# Generated by Django 4.2.13 on 2024-07-21 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="category",
            field=models.ManyToManyField(
                related_name="product_category", to="app.category"
            ),
        ),
    ]
